INSERT INTO clues (clue_string, answer_string, question_type) VALUES
-- Famous People
('The first president of the United States.', 'Washington', 1),
('The physicist who developed the theory of relativity.', 'Einstein', 1),
('The artist who painted the Mona Lisa.', 'DaVinci', 1),
('The founder of Microsoft.', 'Gates', 1),
('The first woman to win a Nobel Prize.', 'Curie', 1),
('The playwright of Romeo and Juliet.', 'Shakespeare', 1),
('The scientist who discovered gravity.', 'Newton', 1),
('The revolutionary leader of Cuba.', 'Castro', 1),
('The first man to walk on the Moon.', 'Armstrong', 1),
('The Queen of England who ruled for 70 years.', 'Elizabeth', 1),

-- Famous Buildings / Landmarks
('A historic clock tower in London.', 'BigBen', 2),
('The tallest building in the world.', 'BurjKhalifa', 2),
('A famous wall that divided Berlin.', 'BerlinWall', 2),
('The leaning tower located in Italy.', 'Pisa', 2),
('An ancient pyramid complex in Egypt.', 'Giza', 2),
('A massive amphitheater in Rome.', 'Colosseum', 2),
('The statue representing liberty in the USA.', 'StatueOfLiberty', 2),
('A famous temple complex in Cambodia.', 'AngkorWat', 2),
('A palace in France known for its hall of mirrors.', 'Versailles', 2),
('A former Incan city in Peru.', 'MachuPicchu', 2),

-- History
('The war between the North and South in the USA.', 'CivilWar', 3),
('The year the Titanic sank.', '1912', 3),
('The emperor of France who was exiled to Elba.', 'Napoleon', 3),
('The document that freed American slaves.', 'Emancipation', 3),
('The war between Athens and Sparta.', 'Peloponnesian', 3),
('The country where the Industrial Revolution began.', 'Britain', 3),
('The Roman general who became dictator.', 'Caesar', 3),
('The year World War II ended.', '1945', 3),
('The event that sparked World War I.', 'Assassination', 3),
('The empire that built the Great Wall of China.', 'Ming', 3),

-- Animals
('The fastest land animal.', 'Cheetah', 4),
('The largest mammal in the world.', 'BlueWhale', 4),
('The only marsupial found in North America.', 'Opossum', 4),
('A flightless bird native to Africa.', 'Ostrich', 4),
('A reptile known for changing color.', 'Chameleon', 4),
('The mammal known for its ability to echolocate.', 'Bat', 4),
('An amphibian that can regenerate limbs.', 'Salamander', 4),
('A type of bear found in China.', 'Panda', 4),
('A snake that kills by squeezing.', 'Anaconda', 4),
('An antlered animal associated with Christmas.', 'Reindeer', 4),

-- Plants
('A tree known for producing acorns.', 'Oak', 5),
('A flower often associated with romance.', 'Rose', 5),
('A plant used to make chocolate.', 'Cacao', 5),
('A spiky desert plant.', 'Cactus', 5),
('A tree that produces maple syrup.', 'Maple', 5),
('A plant used to brew tea.', 'Camellia', 5),
('A herb commonly used in Italian dishes.', 'Basil', 5),
('A large fruit with a thick green rind.', 'Watermelon', 5),
('The world’s tallest type of grass.', 'Bamboo', 5),
('A plant whose seeds are used for oil and snacks.', 'Sunflower', 5),

-- Minerals
('The hardest natural substance on Earth.', 'Diamond', 6),
('A red gemstone often associated with royalty.', 'Ruby', 6),
('A soft metal used in electrical wiring.', 'Copper', 6),
('A yellow metal used for currency and jewelry.', 'Gold', 6),
('A common table salt mineral.', 'Halite', 6),
('A green gemstone associated with Ireland.', 'Emerald', 6),
('A precious metal used in mirrors and jewelry.', 'Silver', 6),
('A dark volcanic glass.', 'Obsidian', 6),
('A blue gemstone often used in jewelry.', 'Sapphire', 6),
('A black fossil fuel.', 'Coal', 6),

-- Planets / Astronomy
('The largest planet in the Solar System.', 'Jupiter', 7),
('The red planet.', 'Mars', 7),
('The planet closest to the Sun.', 'Mercury', 7),
('The ringed planet.', 'Saturn', 7),
('The only planet known to support life.', 'Earth', 7),
('The smallest and now dwarf planet.', 'Pluto', 7),
('The force that keeps planets in orbit.', 'Gravity', 7),
('The star at the center of the Solar System.', 'Sun', 7),
('The galaxy we live in.', 'MilkyWay', 7),
('A natural satellite that orbits Earth.', 'Moon', 7),

-- Music and Art
('The composer of the Ninth Symphony.', 'Beethoven', 9),
('The artist known for painting Starry Night.', 'VanGogh', 9),
('The genre of music originating from New Orleans.', 'Jazz', 9),
('The instrument with 88 keys.', 'Piano', 9),
('The style of painting used by Monet.', 'Impressionism', 9),
('The musical scale with do, re, mi.', 'Solfege', 9),
('A brass instrument with a slide.', 'Trombone', 9),
('The artist known for Cubism.', 'Picasso', 9),
('The Beatles were from this country.', 'UK', 9),
('The opera featuring the character Carmen.', 'Carmen', 9),

-- Geography
('The longest river in the world.', 'Nile', 10),
('The capital of Japan.', 'Tokyo', 10),
('The continent with the Amazon rainforest.', 'SouthAmerica', 10),
('The country known for the Great Wall.', 'China', 10),
('The world’s largest ocean.', 'Pacific', 10),
('The coldest continent.', 'Antarctica', 10),
('The country that invented pizza.', 'Italy', 10),
('The city known as the Big Apple.', 'NewYork', 10),
('The highest mountain on Earth.', 'Everest', 10),
('The country with the most lakes.', 'Canada', 10);
