-- Corrected \"Famous People\" entries with more descriptive answers (questiontype_id = 1)
INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('The first president of the United States.', 'George Washington', 1),
('The physicist who developed the theory of relativity.', 'Albert Einstein', 1),
('The artist who painted the Mona Lisa.', 'Leonardo da Vinci', 1),
('The founder of Microsoft.', 'Bill Gates', 1),
('The first woman to win a Nobel Prize.', 'Marie Curie', 1),
('The playwright of Romeo and Juliet.', 'William Shakespeare', 1),
('The scientist who discovered gravity.', 'Isaac Newton', 1),
('The revolutionary leader of Cuba.', 'Fidel Castro', 1),
('The first man to walk on the Moon.', 'Neil Armstrong', 1),
('The Queen of England who ruled for 70 years.', 'Elizabeth II', 1),
('The first Black president of the United States.', 'Barack Obama', 1),
('The inventor of the telephone.', 'Alexander Graham Bell', 1),
('The founder of psychoanalysis.', 'Sigmund Freud', 1),
('The philosopher who taught Alexander the Great.', 'Aristotle', 1),
('The inventor of the polio vaccine.', 'Jonas Salk', 1),
('The author of \"Frankenstein.\"', 'Mary Shelley', 1),
('The first female Prime Minister of the UK.', 'Margaret Thatcher', 1),
('South Africa\'s first democratically elected president.', 'Nelson Mandela', 1),
('Longest-serving First Lady of the US, champion of civil rights.', 'Eleanor Roosevelt', 1),
('The King of Pop.', 'Michael Jackson', 1),
('A comedic genius of the silent film era.', 'Charlie Chaplin', 1),
('A tennis legend with 23 major singles titles.', 'Serena Williams', 1),
('One of the greatest footballers, nicknamed \"The King of Football.\"', 'Pelé', 1),
('\"The Greatest\" boxer who changed his name from Cassius Clay.', 'Muhammad Ali', 1),
('The founder of Amazon.', 'Jeff Bezos', 1),
('The founder of Facebook.', 'Mark Zuckerberg', 1),
('\"The Lady with the Lamp,\" pioneer of modern nursing.', 'Florence Nightingale', 1),
('The first female pilot to fly solo across the Atlantic.', 'Amelia Earhart', 1),
('Leader of India\'s nonviolent independence movement.', 'Mahatma Gandhi', 1),
('Led the US civil rights movement, gave \"I Have a Dream.\"', 'Martin Luther King Jr.', 1),
('An English theoretical physicist with ALS, wrote \"A Brief History of Time.\"', 'Stephen Hawking', 1),
('The Greek philosopher who taught Plato.', 'Socrates', 1),
('The British Prime Minister during WWII.', 'Winston Churchill', 1),
('The comedic actor known for playing Mr. Bean.', 'Rowan Atkinson', 1),
('The co-founder of Apple, credited with the iPhone.', 'Steve Jobs', 1),
('The actress who starred in \"Breakfast at Tiffany\'s.\"', 'Audrey Hepburn', 1),
('The first woman to summit Mount Everest.', 'Junko Tabei', 1),
('The Swedish teen who started the global climate strike.', 'Greta Thunberg', 1),
('The youngest Nobel Prize laureate for female education advocacy.', 'Malala Yousafzai', 1),
('The ancient Greek \"Father of Medicine.\"', 'Hippocrates', 1),
('The actress known for playing Cleopatra, with violet eyes.', 'Elizabeth Taylor', 1),
('The Jamaican sprinter known as the fastest man in the world.', 'Usain Bolt', 1),
('The comedian who directed \"Blazing Saddles.\"', 'Mel Brooks', 1),
('The philosopher who wrote \"The Republic.\"', 'Plato', 1),
('The \"Father of the Computer,\" invented the first mechanical computer.', 'Charles Babbage', 1),
('The second President of the United States, a Founding Father.', 'John Adams', 1),
('The Roman general turned dictator, assassinated in 44 BC.', 'Julius Caesar', 1),
('The Chinese philosopher known for \"The Analects.\"', 'Confucius', 1),
('The 16th US President, led the nation through the Civil War.', 'Abraham Lincoln', 1),
('The comedic actress famous for \"I Love Lucy.\"', 'Lucille Ball', 1);

-- Famous Buildings / Landmarks
-- Revised \"Famous Buildings / Landmarks\" with multi-word answers (questiontype_id = 2)
INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('A historic clock tower in London.', 'Big Ben', 2),
('The tallest building in the world.', 'Burj Khalifa', 2),
('A famous wall that divided Berlin.', 'Berlin Wall', 2),
('The leaning tower located in Italy.', 'Leaning Tower of Pisa', 2),
('An ancient pyramid complex in Egypt.', 'Giza Pyramids', 2),
('A massive amphitheater in Rome.', 'Colosseum', 2),
('The statue representing liberty in the USA.', 'Statue of Liberty', 2),
('A famous temple complex in Cambodia.', 'Angkor Wat', 2),
('A palace in France known for its hall of mirrors.', 'Palace of Versailles', 2),
('A former Incan city in Peru.', 'Machu Picchu', 2),
('A luxurious hotel in the UAE shaped like a sail.', 'Burj Al Arab', 2),
('A UNESCO World Heritage mosque-cathedral in Spain.', 'Mezquita de Córdoba', 2),
('A historic symbol of love in India, built by Shah Jahan.', 'Taj Mahal', 2),
('An iconic opera house in Sydney Harbour.', 'Sydney Opera House', 2),
('A palace in Beijing whose name means \"Forbidden Palace.\"', 'Forbidden City', 2),
('A massive statue of Jesus overlooking Rio de Janeiro.', 'Christ the Redeemer', 2),
('A medieval fortress in Russia, home to the president.', 'Moscow Kremlin', 2),
('A monument in Paris completed in 1889.', 'Eiffel Tower', 2),
('A prehistoric monument of standing stones in Wiltshire.', 'Stonehenge', 2),
('A Neolithic site in Malta known for megalithic temples.', 'Hagar Qim', 2),
('A Moorish fortress-palace in Granada, Spain.', 'Alhambra', 2),
('A rock fortress in Sri Lanka featuring ancient frescoes.', 'Sigiriya Rock', 2),
('A Gothic cathedral in the heart of Milan.', 'Milan Duomo', 2),
('A Buddhist temple complex in Java, Indonesia.', 'Borobudur Temple', 2),
('A city in Jordan carved into red sandstone cliffs.', 'Petra', 2),
('The seat of the Japanese Emperor in Tokyo.', 'Imperial Palace', 2),
('A massive Neoclassical temple in Athens.', 'Parthenon', 2),
('A vast fortress complex in Moscow with red walls.', 'Red Square Complex', 2),
('An ancient city in Tunisia used as a setting in Star Wars.', 'Matmata', 2),
('A UNESCO site in Ethiopia known for rock-hewn churches.', 'Lalibela Churches', 2),
('A sacred Shinto shrine on Itsukushima Island.', 'Itsukushima Shrine', 2),
('A basilica in Barcelona designed by Gaudí.', 'Sagrada Família', 2),
('A memorial in Washington D.C. shaped like a tall obelisk.', 'Washington Monument', 2),
('A medieval castle in Germany said to inspire Disney.', 'Neuschwanstein Castle', 2),
('A famous round amphitheater in Tunisia.', 'El Jem Amphitheatre', 2),
('A temple dedicated to Artemis, one of the Seven Wonders.', 'Temple of Artemis at Ephesus', 2),
('An island prison off San Francisco Bay, now a museum.', 'Alcatraz Island', 2),
('A golden shrine in Punjab, the holiest Gurdwara of Sikhism.', 'Golden Temple', 2),
('A fortress built by the Aztecs near Mexico City.', 'Tenochtitlan Fortress', 2),
('A massive prehistoric cave complex in France with ancient paintings.', 'Lascaux Caves', 2),
('A castle in Transylvania associated with Vlad the Impaler.', 'Bran Castle', 2),
('A tall, pointed structure in St. Louis, called \"Gateway to the West.\"', 'Gateway Arch', 2),
('A unique mud-brick mosque in Djenné, Mali.', 'Great Mosque of Djenné', 2),
('A 1930s skyscraper in NYC known for its Art Deco design.', 'Chrysler Building', 2),
('A shrine in Kyoto known for its thousands of torii gates.', 'Fushimi Inari Taisha', 2),
('A basilica atop Montmartre in Paris, built in Romano-Byzantine style.', 'Sacré Cœur', 2),
('A famous gateway in Mumbai, built to commemorate King George V\'s visit.', 'Gateway of India', 2),
('An underwater marine shrine in Key Largo, Florida.', 'Christ of the Abyss', 2);

-- Revised \"History\" entries with multi-word answers (questiontype_id = 3)
INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('The war between the North and South in the USA.', 'American Civil War', 3),
('The year the Titanic sank.', '1912', 3),
('The emperor of France who was exiled to Elba.', 'Napoleon Bonaparte', 3),
('The document that freed American slaves.', 'Emancipation Proclamation', 3),
('The war between Athens and Sparta.', 'Peloponnesian War', 3),
('The country where the Industrial Revolution began.', 'Great Britain', 3),
('The Roman general who became dictator.', 'Julius Caesar', 3),
('The year World War II ended.', '1945', 3),
('The event that sparked World War I.', 'Assassination of Franz Ferdinand', 3),
('The empire that built the Great Wall of China.', 'Ming Dynasty', 3),
('The day the Magna Carta was sealed (Year).', '1215', 3),
('The king who built the Hanging Gardens of Babylon.', 'Nebuchadnezzar II', 3),
('The ancient city destroyed by Mount Vesuvius in AD 79.', 'Pompeii', 3),
('The Greek conqueror who built a vast empire by 323 BC.', 'Alexander the Great', 3),
('The year Columbus reached the Americas.', '1492', 3),
('The Persian king who invaded Greece in 480 BC.', 'Xerxes I', 3),
('The Chinese admiral who sailed as far as Africa in the 15th century.', 'Zheng He', 3),
('The year the Berlin Wall fell.', '1989', 3),
('The civilization that created the earliest known code of laws.', 'Babylonian Empire', 3),
('The year Martin Luther posted his 95 Theses.', '1517', 3),
('The day the Bastille was stormed in the French Revolution (Year).', '1789', 3),
('The empire that controlled most of South Asia from 1526 to 1857.', 'Mughal Empire', 3),
('The year India gained independence from Britain.', '1947', 3),
('The ancient Egyptian queen allied with Julius Caesar and Mark Antony.', 'Cleopatra VII', 3),
('The year Hitler rose to power in Germany.', '1933', 3),
('The city in Italy devastated by the Great Plague in 1348.', 'Florence', 3),
('The year the US declared independence from Britain.', '1776', 3),
('The earliest known civilization in Mesopotamia.', 'Sumerians', 3),
('The first female pharaoh who expanded trade in ancient Egypt.', 'Hatshepsut', 3),
('The city conquered by the Ottomans in 1453, formerly Constantinople.', 'Istanbul', 3),
('The Greek philosopher tried and executed in 399 BC.', 'Socrates', 3),
('The war from 1950 to 1953 in East Asia.', 'Korean War', 3),
('The year Johannes Gutenberg pioneered the printing press.', '1440', 3),
('The last Tsar of Russia, overthrown in 1917.', 'Nicholas II', 3),
('The African trading empire known for its rock-hewn churches.', 'Kingdom of Axum', 3),
('The series of routes connecting China to the Mediterranean.', 'Silk Road', 3),
('The event in October 1929 that triggered the Great Depression.', 'Wall Street Crash', 3),
('The American law passed in 1964, banning racial discrimination.', 'Civil Rights Act', 3),
('The year the Western Roman Empire fell.', '476 AD', 3),
('The religious figure who started the Protestant Reformation in Germany.', 'Martin Luther', 3),
('The global conflict from 1914 to 1918.', 'World War I', 3),
('The Chinese dynasty from 960 to 1279 that invented paper money.', 'Song Dynasty', 3),
('The year Jamestown, the first permanent English colony, was founded.', '1607', 3),
('The year the Great Fire of London took place.', '1666', 3),
('The English queen known as the \"Virgin Queen.\"', 'Elizabeth I', 3),
('The African empire ruled by Mansa Musa, famed for wealth and trade.', 'Mali Empire', 3),
('The year the Black Death began ravaging Europe.', '1347', 3),
('The document that ended WWI in 1919.', 'Treaty of Versailles', 3),
('The event that divided Germany into East and West after WWII.', 'Potsdam Agreement', 3),
('The treaty that sold Louisiana to the United States in 1803.', 'Louisiana Purchase', 3);

-- Animals
INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('The fastest land animal.', 'Cheetah', 4),
('The largest mammal in the world.', 'Blue Whale', 4),
('The only marsupial found in North America.', 'Opossum', 4),
('A flightless bird native to Africa.', 'Ostrich', 4),
('A reptile known for changing color.', 'Chameleon', 4),
('The mammal known for its ability to echolocate.', 'Bat', 4),
('An amphibian that can regenerate limbs.', 'Salamander', 4),
('A type of bear found in China.', 'Panda', 4),
('A snake that kills by squeezing.', 'Anaconda', 4),
('An antlered animal associated with Christmas.', 'Reindeer', 4),
('A black-and-white striped horse-like animal.', 'Zebra', 4),
('A bird that cannot fly but swims in the cold.', 'Penguin', 4),
('A large reptile that lives in swamps and rivers.', 'Crocodile', 4),
('A small animal known for its ability to roll into a ball.', 'Armadillo', 4),
('A dog breed known for its sled-pulling abilities.', 'Husky', 4),
('A marsupial that hops and carries its young in a pouch.', 'Kangaroo', 4),
('A large snake that kills its prey by squeezing.', 'Boa Constrictor', 4),
('A brightly colored bird known for its ability to mimic speech.', 'Parrot', 4),
('A marine mammal known for its intelligence and echolocation.', 'Dolphin', 4),
('A slow-moving mammal that spends most of its life hanging from trees.', 'Sloth', 4),
('An insect known for its ability to produce honey.', 'Bee', 4),
('A nocturnal bird known for its ability to rotate its head nearly 360 degrees.', 'Owl', 4),
('A large cat species that is an excellent climber.', 'Leopard', 4),
('A sea creature with eight arms.', 'Octopus', 4),
('A small, spiky mammal that curls into a ball when threatened.', 'Hedgehog', 4),
('A bird that is often associated with delivering babies.', 'Stork', 4),
('A large mammal that sleeps through the winter.', 'Bear', 4),
('A black-and-white bear known for eating bamboo.', 'Panda', 4),
('A venomous snake known for its hood.', 'Cobra', 4),
('A fast-running bird that cannot fly.', 'Ostrich', 4),
('A fish that can inflate itself into a ball as a defense mechanism.', 'Pufferfish', 4),
('A large mammal known for its long trunk.', 'Elephant', 4),
('A small, burrowing mammal with large ears found in Africa.', 'Aardvark', 4),
('An amphibian that can live both in water and on land.', 'Frog', 4),
('A mammal that lays eggs.', 'Platypus', 4),
('A type of lizard that can detach its tail when threatened.', 'Gecko', 4),
('A large marine animal with tusks and thick blubber.', 'Walrus', 4),
('A small mammal known for its ability to glide between trees.', 'Sugar Glider', 4),
('A reptile with a hard shell that moves very slowly.', 'Tortoise', 4),
('A sea creature that has no brain and drifts with ocean currents.', 'Jellyfish', 4),
('A bird of prey known for its powerful eyesight.', 'Eagle', 4),
('A marsupial found in Australia that spends most of its time sleeping.', 'Koala', 4),
('A black-and-white marine predator known for its dorsal fin.', 'Orca', 4),
('A small rodent that loves to store food in its cheek pouches.', 'Hamster', 4),
('A mammal with a distinctive black mask and ringed tail.', 'Raccoon', 4),
('A sea mammal known for its whiskers and playful nature.', 'Seal', 4),
('A large reptile with a powerful tail and armored body.', 'Alligator', 4),
('A nocturnal flying mammal.', 'Bat', 4),
('An insect known for its ability to jump long distances.', 'Grasshopper', 4),
('A brightly colored frog known for its toxic skin.', 'Poison Dart Frog', 4);

-- Revised \"Plants\" entries with multi-word answers (questiontype_id = 5)
INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('A tree known for producing acorns.', 'Oak Tree', 5),
('A flower often associated with romance.', 'Red Rose', 5),
('A plant used to make chocolate.', 'Cacao Tree', 5),
('A spiky desert plant.', 'Prickly Cactus', 5),
('A tree that produces maple syrup.', 'Sugar Maple', 5),
('A plant used to brew tea.', 'Camellia Sinensis', 5),
('A herb commonly used in Italian dishes.', 'Sweet Basil', 5),
('A large fruit with a thick green rind.', 'Watermelon Fruit', 5),
('The world\'s tallest type of grass.', 'Giant Bamboo', 5),
('A plant whose seeds are used for oil and snacks.', 'Sunflower Plant', 5),
('An orchid used to produce a flavouring for ice cream and cakes.', 'Vanilla Orchid', 5),
('A tropical plant with starchy tubers commonly used in Polynesian cuisine.', 'Taro Root', 5),
('The largest flower in the world, known for its corpse-like odour.', 'Rafflesia Arnoldii', 5),
('A leguminous plant used to produce tofu and soy sauce.', 'Soybean Plant', 5),
('A root vegetable known for its bright orange colour.', 'Orange Carrot', 5),
('A spice derived from the inner bark of a tree.', 'Ceylon Cinnamon', 5),
('A tuberous root vegetable with sweet, starchy flesh.', 'Sweet Potato', 5),
('A small red fruit known for its high vitamin C content.', 'Garden Strawberry', 5),
('A pungent bulb used to flavour dishes worldwide.', 'Garlic Bulb', 5),
('A succulent known for its healing gel.', 'Aloe Vera', 5),
('A tall palm that yields sugary sap used in cooking.', 'Sugar Palm', 5),
('A plant whose seeds are ground to make mustard.', 'Mustard Plant', 5),
('A spice commonly used in curry, derived from the Curcuma longa root.', 'Ground Turmeric', 5),
('A tall coastal grass often used for baskets and thatching.', 'Common Reed', 5),
('A tropical fruit with a spiny exterior and sweet yellow flesh.', 'Ripe Pineapple', 5),
('A climbing vine with bright orange flowers, often grown ornamentally.', 'Trumpet Vine', 5),
('A tall ornamental grass commonly used in landscaping.', 'Pampas Grass', 5),
('An aquatic plant with large circular leaves capable of supporting a child.', 'Victoria Amazonica', 5),
('A legume known for its pods with small round seeds used in soups.', 'Garden Pea', 5),
('A fruit with spiky skin and strong odour, revered in Southeast Asia.', 'Durian Fruit', 5),
('An evergreen shrub with purple flowers, prized for its calming scent.', 'English Lavender', 5),
('A fruit known as the \"Chinese gooseberry,\" with fuzzy brown skin.', 'Kiwi Fruit', 5),
('A starchy tuber that can be processed into flour or tapioca.', 'Cassava Root', 5),
('A leafy green used in salads, known for high iron content.', 'Spinach Leaves', 5),
('A rhizome with a spicy taste, widely used in Asian cuisine.', 'Fresh Ginger', 5),
('A trailing vine that produces edible cylindrical green fruits.', 'Green Cucumber', 5),
('A coniferous tree whose seeds are eaten as \"nuts.\"', 'Pine Tree', 5),
('A fresh herb with curled or flat leaves, often used as a garnish.', 'Common Parsley', 5),
('A bright red fruit often mistaken for a vegetable.', 'Ripe Tomato', 5),
('A cereal crop that is a staple food for half the global population.', 'Asian Rice', 5),
('A climbing legume producing pods known as green beans.', 'Green Bean Plant', 5),
('A tall spadix flower that emits a foul odour, also called the corpse flower.', 'Titan Arum', 5),
('A starchy root commonly known as cocoyam in parts of Africa.', 'Taro Cocoyam', 5),
('A special type of oak whose bark is harvested for wine corks.', 'Cork Oak', 5),
('A large, stiff succulent used to produce tequila.', 'Blue Agave', 5),
('A spice made from the dried seeds of Cuminum cyminum.', 'Ground Cumin', 5),
('A pungent green paste used in sushi, made from a rhizomatous herb.', 'Fresh Wasabi', 5),
('A shrub that produces seeds used to make the world\'s favourite beverage.', 'Coffee Plant', 5),
('A plant whose bulb is a kitchen staple for countless dishes.', 'Brown Onion', 5);

-- Revised \"Minerals\" entries with multi-word answers (questiontype_id = 6)
INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('The hardest natural substance on Earth.', 'Natural Diamond', 6),
('A red gemstone often associated with royalty.', 'Ruby', 6),
('A soft metal used in electrical wiring.', 'Copper', 6),
('A yellow metal used for currency and jewelry.', 'Gold', 6),
('A common table salt mineral.', 'Halite', 6),
('A green gemstone associated with Ireland.', 'Emerald', 6),
('A precious metal used in mirrors and jewelry.', 'Silver', 6),
('A dark volcanic glass.', 'Obsidian', 6),
('A blue gemstone often used in jewelry.', 'Sapphire', 6),
('A hard black fossil fuel.', 'Coal', 6),
('A soft sulfate mineral widely used for plaster.', 'Gypsum', 6),
('A mercury sulfide mineral known for its bright red colour.', 'Cinnabar', 6),
('A green copper carbonate mineral often used as a gemstone.', 'Malachite', 6),
('A banded iron stone famed for rust-red stripes.', 'Tiger Iron', 6),
('A highly magnetic iron ore mineral.', 'Magnetite', 6),
('A hard form of coal with the highest carbon content.', 'Anthracite', 6),
('A purple variety of quartz used in jewelry.', 'Amethyst', 6),
('A hydrated silica gemstone with a distinctive play of colour.', 'Opal', 6),
('A colour-changing variety of chrysoberyl discovered in Russia.', 'Alexandrite', 6),
('A bright blue-to-green mineral used in Southwest jewellery.', 'Turquoise', 6),
('A fluorescent calcium fluoride crystal in various colours.', 'Fluorite', 6),
('A metallic grey iron oxide mineral also called \"bloodstone.\"', 'Hematite', 6),
('The crystalline form of aluminum oxide (found in rubies/sapphires).', 'Corundum', 6),
('A carbon polymorph said to be harder than diamond.', 'Lonsdaleite', 6),
('A fibrous magnesium silicate once widely used for insulation.', 'Asbestos', 6),
('A brilliant green variety of garnet found in Tanzania.', 'Tsavorite', 6),
('A pink manganese silicate mineral, often mottled or banded.', 'Rhodonite', 6),
('A phosphate mineral that may be green, blue, or yellow, used in gems.', 'Apatite', 6),
('A phosphate mineral that darkens when exposed to light.', 'Vivianite', 6),
('A bright green aluminum phosphate mineral with vitreous lustre.', 'Variscite', 6),
('A transparent variety of gypsum known for its lustrous crystals.', 'Selenite', 6),
('A coarse-grained metamorphic rock with alternating layers.', 'Banded Gneiss', 6),
('An aluminium ore essential for metal production.', 'Bauxite Ore', 6),
('A brown iron oxide mineral forming needle-like crystals.', 'Goethite', 6),
('A magnesium-rich carbonate rock used in construction.', 'Dolomite', 6),
('A banded variety of microcrystalline quartz often polished.', 'Banded Agate', 6),
('A fossilized tree resin used to make jewellery.', 'Amber', 6),
('A feldspar with an iridescent sheen, often bluish.', 'Labradorite', 6),
('A pink variety of beryl, sister to emerald.', 'Morganite', 6),
('A copper iron sulfide mineral with a brassy-gold appearance.', 'Chalcopyrite', 6),
('A hydrated magnesium silicate known as the softest mineral.', 'Talc', 6),
('A potassium chloride mineral closely related to rock salt.', 'Sylvite', 6),
('A lead sulfide mineral and the primary ore of lead.', 'Galena', 6),
('A barium sulfate mineral sometimes forming \"desert rose.\"', 'Barite', 6),
('An iron sulfide commonly known as \"fool\'s gold.\"', 'Iron Pyrite', 6),
('A metamorphic rock used by ancient Greeks for sculpture.', 'Marble', 6),
('A calcium carbonate mineral forming rhombohedral crystals.', 'Calcite', 6),
('A polymorph of calcite often found in mollusc shells.', 'Aragonite', 6),
('A variety of layered quartz historically used for cameos.', 'Layered Onyx', 6),
('A magnesium carbonate mineral, typically white, used for refractory.', 'Magnesite', 6);

-- Revised \"Planets / Astronomy\" entries with multi-word answers (questiontype_id = 7)
INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('The largest planet in the Solar System.', 'Planet Jupiter', 7),
('The red planet.', 'Planet Mars', 7),
('The planet closest to the Sun.', 'Planet Mercury', 7),
('The ringed planet.', 'Planet Saturn', 7),
('The only planet known to support life.', 'Planet Earth', 7),
('The smallest and now dwarf planet.', 'Dwarf Pluto', 7),
('The force that keeps planets in orbit.', 'Gravitational Force', 7),
('The star at the center of the Solar System.', 'The Sun', 7),
('The galaxy we live in.', 'Milky Way Galaxy', 7),
('A natural satellite that orbits Earth.', 'Earth\'s Moon', 7),
('The phenomenon where the Moon fully or partially blocks the Sun.', 'Solar Eclipse', 7),
('The phenomenon where Earth\'s shadow covers the Moon.', 'Lunar Eclipse', 7),
('The second planet from the Sun, shrouded in a dense atmosphere.', 'Planet Venus', 7),
('The seventh planet from the Sun, tilted on its side.', 'Planet Uranus', 7),
('The eighth planet from the Sun, known for supersonic winds.', 'Planet Neptune', 7),
('A region of icy objects beyond Neptune, home to Pluto.', 'Kuiper Belt', 7),
('A spherical shell of comets surrounding the Solar System.', 'Oort Cloud', 7),
('A famous comet visible from Earth about every 76 years.', 'Halley\'s Comet', 7),
('A region of rocky debris between Mars and Jupiter.', 'Asteroid Belt', 7),
('A dwarf planet in the asteroid belt, discovered in 1801.', 'Dwarf Ceres', 7),
('The classification of our Sun as a medium-sized star.', 'G-Type Star', 7),
('The largest volcano in the Solar System, located on Mars.', 'Olympus Mons', 7),
('The outermost layer of the Sun, visible during total eclipses.', 'Solar Corona', 7),
('The persistent high-pressure storm on Jupiter.', 'Great Red Spot', 7),
('The path a planet follows around the Sun.', 'Planetary Orbit', 7),
('The shape of a planet\'s orbit, per Kepler\'s first law.', 'Elliptical Orbit', 7),
('Saturn\'s largest moon, with thick nitrogen atmosphere.', 'Moon Titan', 7),
('Jupiter\'s largest moon, bigger than Mercury.', 'Moon Ganymede', 7),
('The line dividing daylight from darkness on Earth.', 'Day-Night Terminator', 7),
('Charged particles colliding with Earth\'s atmosphere, creating lights.', 'Aurora Borealis', 7),
('The shift in wavelength toward red when objects move away.', 'Cosmic Redshift', 7),
('The shift in wavelength toward blue when objects move closer.', 'Cosmic Blueshift', 7),
('The boundary where the Sun\'s solar wind stops.', 'Heliopause Region', 7),
('The law describing galaxies receding proportionally to their distance.', 'Hubble\'s Law', 7),
('A dwarf planet in the scattered disc, larger than Pluto.', 'Dwarf Eris', 7),
('Kepler\'s law stating equal areas are swept out in equal times.', 'Kepler\'s Second Law', 7),
('A star\'s brightness as seen from Earth.', 'Apparent Magnitude', 7),
('A star\'s brightness if placed at 10 parsecs away.', 'Absolute Magnitude', 7),
('The closest star system to our Solar System.', 'Alpha Centauri', 7),
('The supermassive black hole at the center of the Milky Way.', 'Sagittarius A*', 7),
('The brightest star in Earth\'s night sky.', 'Star Sirius', 7),
('The point in a planet\'s orbit closest to the Sun.', 'Orbital Perihelion', 7),
('The point in a planet\'s orbit farthest from the Sun.', 'Orbital Aphelion', 7),
('The NASA space telescope launched in 1990.', 'Hubble Telescope', 7),
('The apparent shift in a star\'s position due to Earth\'s orbit.', 'Stellar Parallax', 7),
('The largest impact basin on Mercury.', 'Caloris Basin', 7),
('The ring system discovered around an ice giant besides Saturn.', 'Rings of Uranus', 7),
('The total solar eclipse in 1919 that supported relativity.', '1919 Eclipse', 7),
('A star cluster called the Seven Sisters in Taurus.', 'The Pleiades', 7),
('The bright star at the end of the Little Dipper\'s handle.', 'Polaris Star', 7);

-- Revised \"Music and Art\" (questiontype_id = 9) with minimal duplication

INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('The composer of the Ninth Symphony.', 'Beethoven', 9),
('The artist known for painting Starry Night.', 'Van Gogh', 9),
('The genre of music originating from New Orleans.', 'Jazz', 9),
('The instrument with 88 keys.', 'Piano', 9),
('The style of painting used by Monet.', 'Impressionism', 9),
('The musical scale with do, re, mi.', 'Solfège', 9),
('A brass instrument with a slide.', 'Trombone', 9),
('The artist known for Cubism.', 'Picasso', 9),
('The Beatles were from this country.', 'UK', 9),
('A famous opera set in Seville, Spain.', 'Carmen', 9),
('The composer of \"The Four Seasons.\"', 'Vivaldi', 9),
('The dance form originating in Renaissance Italy, later codified in France.', 'Ballet', 9),
('A Surrealist artist known for melting clocks.', 'Dalí', 9),
('An art movement characterized by geometric shapes, pioneered by Picasso.', 'Cubism', 9),
('A Baroque composer famous for the Brandenburg Concertos.', 'Bach', 9),
('The Spanish \"father\" of the guitar concerto, wrote \"Concierto de Aranjuez.\"', 'Rodrigo', 9),
('A 20th-century Russian composer of \"The Rite of Spring.\"', 'Stravinsky', 9),
('A painting technique using tiny dots of colour, developed by Seurat.', 'Pointillism', 9),
('The major Renaissance artist who painted the School of Athens.', 'Raphael', 9),
('An early jazz trumpeter nicknamed \"Satchmo.\"', 'Armstrong', 9),
('A stringed instrument held between the knees and played with a bow.', 'Cello', 9),
('An Austrian composer known for \"Don Giovanni\" and \"Figaro.\"', 'Mozart', 9),
('A Romantic composer known for the \"Minute Waltz.\"', 'Chopin', 9),
('The painter of \"American Gothic.\"', 'Grant Wood', 9),
('The instrument that \"speaks\" via a keyboard controlling pipes.', 'Organ', 9),
('A Dutch painter who created \"Girl with a Pearl Earring.\"', 'Vermeer', 9),
('The style combining African-American work songs and European harmony.', 'Blues', 9),
('A shape-note singing tradition from the rural South of the USA.', 'Sacred Harp', 9),
('A Chinese-American cellist with eclectic collaborations.', 'Yo-Yo Ma', 9),
('The 18th-century composer of the oratorio \"Messiah.\"', 'Handel', 9),
('A Greek composer recognized for the film score \"Zorba the Greek.\"', 'Theodorakis', 9),
('A Spanish painter known for \"Las Meninas.\"', 'Velázquez', 9),
('An electronic music instrument played without physical contact.', 'Theremin', 9),
('A Russian composer of the \"1812 Overture.\"', 'Tchaikovsky', 9),
('A painting technique using plaster, as seen in the Sistine Chapel.', 'Fresco', 9),
('A musical term for a gradually increasing volume.', 'Crescendo', 9),
('An instrument central to flamenco.', 'Guitar', 9),
('An Austrian composer known for the \"Symphony of a Thousand.\"', 'Mahler', 9),
('An American artist who led the Pop Art movement with soup cans.', 'Warhol', 9),
('The dance style from Argentina and Uruguay, featuring close embrace.', 'Tango', 9),
('A style of rhythmic urban music from the Bronx.', 'Hip Hop', 9),
('A Neapolitan song often associated with Italian tenors.', 'O Sole Mio', 9),
('A painting of inanimate objects, like fruit or flowers.', 'Still Life', 9),
('A Norwegian artist famous for \"The Scream.\"', 'Munch', 9),
('A music style from Jamaica with syncopated rhythm.', 'Reggae', 9),
('Small pieces of stone or glass forming a picture.', 'Mosaic', 9),
('A jazz saxophonist known for \"Giant Steps.\"', 'Coltrane', 9),
('A West African music genre popularized by Fela Kuti.', 'Afrobeat', 9),
('An art style with bold colours, from 1905-1908.', 'Fauvism', 9),
('An American composer of \"Rhapsody in Blue.\"', 'Gershwin', 9);

-- Revised \"Geography\" with minimal duplication (questiontype_id = 10)

INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('The longest river in the world.', 'Nile', 10),
('The capital of Japan.', 'Tokyo', 10),
('The continent with the Amazon rainforest.', 'South America', 10),
('The country known for the Great Wall.', 'China', 10),
('The world\'s largest ocean.', 'Pacific Ocean', 10),
('The coldest continent.', 'Antarctica', 10),
('The country that invented pizza.', 'Italy', 10),
('The city known as the Big Apple.', 'New York', 10),
('The highest mountain on Earth.', 'Mount Everest', 10),
('The country with the most lakes.', 'Canada', 10),
('The largest desert in the world.', 'Sahara', 10),
('The continent with the largest population.', 'Asia', 10),
('The city famously called the \"City of Love.\"', 'Paris', 10),
('The largest island on Earth by area.', 'Greenland', 10),
('The capital city of Australia.', 'Canberra', 10),
('The capital city of Germany.', 'Berlin', 10),
('The capital city of India.', 'New Delhi', 10),
('The city known for the Christ the Redeemer statue.', 'Rio de Janeiro', 10),
('The country where Machu Picchu is located.', 'Peru', 10),
('The city home to Red Square.', 'Moscow', 10),
('The largest landlocked country.', 'Kazakhstan', 10),
('The longest continental mountain range.', 'Andes', 10),
('The tallest waterfall in the world.', 'Angel Falls', 10),
('The largest city in Africa by population.', 'Lagos', 10),
('The capital city of Egypt.', 'Cairo', 10),
('The country nicknamed \"The Land of the Rising Sun.\"', 'Japan', 10),
('The US state with the highest population.', 'California', 10),
('The largest country by area.', 'Russia', 10),
('The largest peninsula in the world.', 'Arabian', 10),
('The city known as the \"Eternal City.\"', 'Rome', 10),
('The only continent with no permanent human residents.', 'Antarctica', 10),
('The capital city of Iceland.', 'Reykjavik', 10),
('The capital city of Thailand.', 'Bangkok', 10),
('The city nicknamed the \"Pearl of the Orient,\" capital of the Philippines.', 'Manila', 10),
('The busiest container port in the world.', 'Shanghai', 10),
('The second largest continent by area.', 'Africa', 10),
('The country nicknamed the \"Land of a Thousand Lakes.\"', 'Finland', 10),
('The city known for the Golden Gate Bridge.', 'San Francisco', 10),
('The country where the Taj Mahal is located.', 'India', 10),
('The city home to the Eiffel Tower.', 'Paris', 10),
('The largest city in Canada by population.', 'Toronto', 10),
('The capital city of Spain.', 'Madrid', 10),
('The city known for its famous Opera House.', 'Sydney', 10),
('The highest administrative capital city in the world.', 'La Paz', 10),
('The capital city of Kenya.', 'Nairobi', 10),
('The country renowned for its dramatic fjords.', 'Norway', 10),
('The largest salt flat on Earth.', 'Salar de Uyuni', 10),
('The capital city of Ghana.', 'Accra', 10),
('The country historically famous for building pyramids.', 'Egypt', 10),
('The city nicknamed the \"City of Brotherly Love.\"', 'Philadelphia', 10);

-- Sports 
INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('Which bat-and-ball sport is played in Test, ODI, and T20 formats?', 'Cricket', 11),
('Which sport is played with 15 players per side, featuring tries and scrums?', 'Rugby', 11),
('Which version of rugby is played with 13 players per side?', 'Rugby League', 11),
('Which globally popular sport is called \"football\" outside the US?', 'Soccer', 11),
('Which women\'s team sport, similar to basketball, is popular in the Commonwealth?', 'Netball', 11),
('Which trophy is contested between Australia and England in Test cricket?', 'Ashes', 11),
('Which Gaelic team sport uses a round ball punched or kicked into a goal?', 'Gaelic Football', 11),
('Which indoor racket sport is played with a shuttlecock?', 'Badminton', 11),
('Which Irish stick-and-ball sport is considered the fastest field game?', 'Hurling', 11), 
('Which bat-and-ball game, like baseball, is played especially by women in Australia?', 'Softball', 11),
('Which racquet sport uses a small hollow rubber ball in a walled court?', 'Squash', 11),
('Which contact team sport is Australia\'s most attended domestic competition?', 'Aussie Rules', 11),
('Which trophy is awarded to the winner of the Rugby World Cup?', 'Webb Ellis Cup', 11),
('Which distance running event was inspired by an ancient Greek messenger?', 'Marathon', 11),
('Which ball-and-stick sport is known as the \"national game\" of India and Pakistan?', 'Hockey', 11),
('Which sport is played on a lawn or synthetic surface using biased bowls?', 'Lawn Bowls', 11),
('Which combat sport features strikes with fists, regulated in weight classes?', 'Boxing', 11),
('Which race is the oldest active horse race in England, dating to 1776?', 'StLeger', 11),
('Which Commonwealth country is famous for the All Blacks national rugby team?', 'New Zealand', 11),
('Which trophy is contested in netball between Commonwealth nations, named after a monarchy?', 'Netball Quad Series', 11),
('Which major annual tennis event is held at the All England Club?', 'Wimbledon', 11),
('Which Jamaican sprinter holds the men\'s 100m and 200m world records?', 'Bolt', 11),
('Which bat-and-ball sport is specifically designed for visually impaired players?', 'Blind Cricket', 11),
('Which club-based competition is considered England\'s top-tier football league?', 'Premier League', 11),
('Which sport\'s top international prize is the ICC Cricket World Cup?', 'Cricket', 11),
('Which field sport uses sticks curved at one end to hit a hard ball?', 'Hockey', 11),
('Which racket sport sees players drive a small, hollow ball off walls?', 'Squash', 11),
('Which set of multi-sport competitions is also known as the \"Friendly Games?\"', 'Commonwealth Games', 11),
('Which Olympic sport involves fencing, swimming, show jumping, running, and shooting?', 'Modern Pentathlon', 11),
('Which West Indian domestic T20 league is nicknamed \"The Biggest Party in Sport?\"', 'CPL', 11),
('Which women\'s sport is governed internationally by World Netball?', 'Netball', 11),
('Which 7-a-side variant of rugby features shorter matches and is in the Commonwealth Games?', 'Rugby Sevens', 11),
('Which form of motorsport holds the annual Australian Grand Prix?', 'Formula One', 11),
('Which competition is the oldest knockout football tournament in England?', 'FA Cup', 11),
('Which cricket format lasts up to five days, featuring two innings per side?', 'Test Cricket', 11),
('Which summer sport involves hitting a shuttlecock across a net?', 'Badminton', 11),
('Which winter sport is played by sliding stones on ice towards a target?', 'Curling', 11),
('Which lawn game involves hitting wooden balls through hoops with a mallet?', 'Croquet', 11),
('Which side of the scrum does the loosehead prop wear the jersey number 1 in rugby union?', 'Left Side', 11),
('Which style of bowls is played indoors on a carpet or mat?', 'Short Mat Bowls', 11),
('Which doubles racket game involving a tennis-like court originated in England?', 'Paddle Tennis', 11),
('Which muscular endurance sport sees participants push a stone overhead, popular in Scotland?', 'Stone Lifting', 11),
('Which event sees participants cycle multiple laps of a velodrome at high speed?', 'Track Cycling', 11),
('Which national men\'s field hockey team is nicknamed the Kookaburras?', 'Australia', 11),
('Which Commonwealth country\'s soccer league is known as the PSL?', 'South Africa', 11),
('Which sport uses \"innings\" and \"rounders bats,\" especially in British schools?', 'Rounders', 11);

-- Revised \"Movies & TV\" (questiontype_id = 12) with multi-word answers

INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('Which 1939 film follows a Kansas girl traveling over the rainbow?', 'The Wizard of Oz', 12),
('Which 1977 George Lucas film introduced a galaxy far, far away?', 'Star Wars', 12),
('Which 1964 Disney film features a magical nanny flying with an umbrella?', 'Mary Poppins', 12),
('Which 1994 Disney movie follows a lion prince named Simba?', 'The Lion King', 12),
('Which long-running British sci-fi series features a Time Lord and a TARDIS?', 'Doctor Who', 12),
('Which 2001 film introduced the hobbits and the One Ring to global audiences?', 'The Fellowship of the Ring', 12),
('Which sitcom features six friends hanging out at Central Perk in New York?', 'Friends', 12),
('Which 2009 sci-fi movie by Neill Blomkamp is set in Johannesburg?', 'District 9', 12),
('Which 2008 Christopher Nolan film features the Joker played by Heath Ledger?', 'The Dark Knight', 12),
('Which 1972 gangster film was directed by Francis Ford Coppola, starring Marlon Brando?', 'The Godfather', 12),
('Which 2010 thriller by Christopher Nolan dives into layered dreams?', 'Inception', 12),
('Which 1993 dinosaur-themed film was directed by Steven Spielberg?', 'Jurassic Park', 12),
('Which 2003 holiday comedy stars Will Ferrell as a naive Christmas elf?', 'Elf', 12),
('Which 1984 sci-fi film stars Arnold Schwarzenegger as a time-traveling cyborg?', 'The Terminator', 12),
('Which British spy series stars Rowan Atkinson as a bumbling secret agent?', 'Johnny English', 12),
('Which 1999 sci-fi masterpiece introduced the concept of living in a simulation?', 'The Matrix', 12),
('Which American sitcom features genius scientists in Pasadena, including Sheldon?', 'The Big Bang Theory', 12),
('Which 2019 Marvel blockbuster concluded the Infinity Saga?', 'Avengers: Endgame', 12),
('Which 2013 Disney animated musical features two sisters in the kingdom of Arendelle?', 'Frozen', 12),
('Which 1988 action film follows John McClane in the Nakatomi Plaza?', 'Die Hard', 12),
('Which 1975 thriller directed by Steven Spielberg features a giant great white shark?', 'Jaws', 12),
('Which 2009 Clint Eastwood film depicts South Africa\'s 1995 Rugby World Cup triumph?', 'Invictus', 12),
('Which long-running animated series follows the yellow family of Springfield?', 'The Simpsons', 12),
('Which 1979 sci-fi horror film features the crew of the Nostromo?', 'Alien', 12),
('Which British spy film series features 007 and MI6?', 'James Bond', 12),
('Which TV show depicts the medieval fantasy world of Westeros?', 'Game of Thrones', 12),
('Which 1961 musical film was adapted from a Broadway show about rival gangs?', 'West Side Story', 12),
('Which 1995 Pixar movie was the first feature-length computer-animated film?', 'Toy Story', 12),
('Which 1980 horror film by Stanley Kubrick features Jack Torrance in an isolated hotel?', 'The Shining', 12),
('Which 2004 comedy follows four British friends fighting zombies?', 'Shaun of the Dead', 12),
('Which 1962 epic film stars Peter O\'Toole as a British officer in the Middle East?', 'Lawrence of Arabia', 12),
('Which 1992 animated musical is set in the fictional city of Agrabah?', 'Aladdin', 12),
('Which classic 1931 horror film stars Bela Lugosi as a Transylvanian vampire?', 'Dracula', 12),
('Which 1942 Disney film features a fawn growing up in the forest?', 'Bambi', 12),
('Which 1985 time-travel film stars Michael J. Fox as Marty McFly?', 'Back to the Future', 12),
('Which British series follows Sherlock Holmes and Dr. Watson in modern London?', 'Sherlock', 12),
('Which 1982 sci-fi film directed by Steven Spielberg features a gentle alien and a young boy?', 'E.T. the Extra-Terrestrial', 12),
('Which comedic British TV series follows a hapless hotel owner named Basil?', 'Fawlty Towers', 12),
('Which 2001 DreamWorks animated film features an ogre rescuing a princess?', 'Shrek', 12),
('Which 1960 epic film was directed by Stanley Kubrick about a slave revolt in Rome?', 'Spartacus', 12),
('Which American sitcom is set in a Boston bar \"where everybody knows your name?\"', 'Cheers', 12),
('Which 2017 South African film depicts gang violence in the Cape Flats?', 'Five Fingers for Marseilles', 12),
('Which 2014 Marvel film introduced Star-Lord, Gamora, and Rocket?', 'Guardians of the Galaxy', 12),
('Which 1997 James Cameron film features an ill-fated ocean liner?', 'Titanic', 12),
('Which British spy-comedy film stars Colin Firth as an elite secret agent organization?', 'Kingsman', 12),
('Which 1984 fantasy film features a never-ending storybook and Falkor the luckdragon?', 'The NeverEnding Story', 12),
('Which 2017 Hugh Jackman musical celebrates P.T. Barnum\'s show?', 'The Greatest Showman', 12),
('Which TV series follows a paper company in Scranton, adapted from a UK original?', 'The Office', 12),
('Which BBC nature documentary series is narrated by Sir David Attenborough?', 'Planet Earth', 12);

-- Science & Technology (questiontype_id = 13)
-- Revised \"Science & Technology\" (questiontype_id = 13) with multi-word answers

INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('Which English mathematician wrote \"Principia Mathematica,\" formulating the laws of motion?', 'Isaac Newton', 13),
('Which Italian astronomer improved the telescope and supported heliocentrism?', 'Galileo Galilei', 13),
('Which Serbian-American inventor advanced AC electricity supply systems?', 'Nikola Tesla', 13),
('Which theory of planetary orbits did Johannes Kepler propose, describing ellipses?', 'Kepler\'s Laws', 13),
('Which English naturalist proposed the theory of evolution by natural selection?', 'Charles Darwin', 13),
('Which British computer scientist invented the World Wide Web?', 'Tim Berners-Lee', 13),
('Which Polish-French physicist won Nobel Prizes in Physics and Chemistry for radioactivity?', 'Marie Curie', 13),
('Which American inventor created the phonograph and practical electric light bulb?', 'Thomas Edison', 13),
('Which German physicist developed quantum theory, earning a 1918 Nobel Prize?', 'Max Planck', 13),
('Which Austrian physicist gave us the \"cat\" paradox illustrating quantum superposition?', 'Erwin Schrödinger', 13),
('Which 20th-century English scientist co-discovered the structure of DNA with Crick?', 'James Watson', 13),
('Which technology giant was founded by Bill Gates and Paul Allen in 1975?', 'Microsoft Corporation', 13),
('Which 1977 personal computer series was released by Apple?', 'Apple II', 13),
('Which spacecraft became the first to reach interstellar space in 2012?', 'Voyager 1', 13),
('Which British mathematician helped crack the Enigma code in WWII?', 'Alan Turing', 13),
('Which American built the first successful airplane with his brother in 1903?', 'Wright Brothers', 13),
('Which 1947 invention marked the start of the semiconductor era at Bell Labs?', 'The Transistor', 13),
('Which American scientist led the Manhattan Project to develop the atomic bomb?', 'J. Robert Oppenheimer', 13),
('Which German-born physicist wrote the special and general theories of relativity?', 'Albert Einstein', 13),
('Which British physicist discovered the neutron in 1932?', 'James Chadwick', 13),
('Which programming language, developed by Guido van Rossum, emphasizes readability?', 'Python Language', 13),
('Which 1960s global positioning concept is widely used today for navigation?', 'GPS System', 13),
('Which telescope, launched in 1990, has provided deep-space images of distant galaxies?', 'Hubble Space Telescope', 13),
('Which US space program first landed humans on the Moon in 1969?', 'Apollo Program', 13),
('Which American astronomer is famous for the \"Cosmos\" series and promoting SETI?', 'Carl Sagan', 13),
('Which British chemist proposed the structure of benzene using a ring?', 'Friedrich Kekulé', 13),
('Which female British chemist\'s work on DNA was key to discovering its structure?', 'Rosalind Franklin', 13),
('Which concept in computing describes a universal machine by Turing?', 'Turing Machine', 13),
('Which early 19th-century English mathematician is called the \"first computer programmer?\"', 'Ada Lovelace', 13),
('Which American company launched the first iPhone in 2007?', 'Apple Inc.', 13),
('Which American physical chemist discovered fullerenes and shared a 1996 Nobel Prize?', 'Richard Smalley', 13),
('Which mission, launched by NASA in 1977, carried the Golden Record into space?', 'Voyager Program', 13),
('Which British scientist discovered penicillin in 1928?', 'Alexander Fleming', 13),
('Which 1969 event saw Neil Armstrong become the first man on the Moon?', 'Apollo 11', 13),
('Which Swiss-born scientist developed the scale for measuring earthquake magnitude in 1935?', 'Charles Richter', 13),
('Which American entrepreneur co-founded Tesla, SpaceX, and PayPal?', 'Elon Musk', 13),
('Which American molecular biologist invented the polymerase chain reaction (PCR)?', 'Kary Mullis', 13),
('Which German physicist discovered X-rays in 1895, earning the first Nobel Prize in Physics?', 'Wilhelm Röntgen', 13),
('Which Scottish inventor improved the steam engine, powering the Industrial Revolution?', 'James Watt', 13),
('Which British scientist discovered electromagnetic induction in 1831?', 'Michael Faraday', 13),
('Which theory states that galaxies recede from us at speeds proportional to their distance?', 'Hubble\'s Law', 13),
('Which UK-based code-breaking machine automated reading of Enigma messages in WWII?', 'The Bombe', 13),
('Which IBM computer defeated Garry Kasparov at chess in 1997?', 'Deep Blue', 13),
('Which English physicist explained black hole radiation in 1974?', 'Stephen Hawking', 13),
('Which American engineer invented the microprocessor at Intel in 1971?', 'Federico Faggin', 13),
('Which US-based tech giant created the Android mobile operating system?', 'Google LLC', 13),
('Which UK-based open-source microcomputer foundation launched a tiny board in 2012?', 'Raspberry Pi', 13),
('Which 1957 Soviet satellite was the first artificial Earth satellite?', 'Sputnik 1', 13),
('Which nuclear physicist was known as the \"father of the hydrogen bomb?\"', 'Edward Teller', 13);

-- Mythology & Folklore (questiontype_id = 14)
INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('The king of the gods in Greek mythology, wielding thunderbolts.', 'Zeus', 14),
('The Roman equivalent of the Greek god Zeus.', 'Jupiter', 14),
('The one-eyed Allfather in Norse mythology.', 'Odin', 14),
('The Greek hero who completed the Twelve Labours.', 'Heracles', 14),
('The monstrous bull-headed creature in Crete.', 'Minotaur', 14),
('The Norse thunder god who wields Mjölnir.', 'Thor', 14),
('The legendary founder of Rome, raised by a she-wolf.', 'Romulus', 14),
('The Greek goddess of wisdom, war strategy, and weaving.', 'Athena', 14),
('The goddess of love and beauty in Greek myth, born from sea foam.', 'Aphrodite', 14),
('The Celtic mother goddess associated with fertility.', 'Danu', 14),
('The winged horse of Greek mythology, born from Medusa\'s blood.', 'Pegasus', 14),
('The Titan who stole fire for humanity in Greek myth.', 'Prometheus', 14),
('The final battle of gods and giants in Norse mythology.', 'Ragnarok', 14),
('The Roman goddess of love, counterpart to Aphrodite.', 'Venus', 14),
('The Norse goddess presiding over the realm of the dead.', 'Hel', 14),
('The monstrous wolf in Norse myth, destined to slay Odin.', 'Fenrir', 14),
('The Greek hero who slew the Minotaur.', 'Theseus', 14),
('The Norse goddess of fertility and love, sister of Freyr.', 'Freyja', 14),
('The Greek hero with a vulnerable heel.', 'Achilles', 14),
('The witch of Slavic folklore who lives in a hut on chicken legs.', 'Baba Yaga', 14),
('The Greek goddess of victory, namesake of a sports brand.', 'Nike', 14),
('The Egyptian god of the underworld who judges souls.', 'Osiris', 14),
('The giant serpent encircling Midgard in Norse myth.', 'Jormungandr', 14),
('The queen of the gods in Roman mythology, wife of Jupiter.', 'Juno', 14),
('The master craftsman who built the Labyrinth in Greek myth.', 'Daedalus', 14),
('The Celtic festival marking the start of winter, precursor to Halloween.', 'Samhain', 14),
('A half-man, half-goat creature in Greek mythology, companion of Dionysus.', 'Satyr', 14),
('The Celtic warrior queen who led a revolt against Roman occupation.', 'Boudica', 14),
('The Roman god of war, father of Romulus and Remus.', 'Mars', 14),
('The Greek hero who beheaded Medusa.', 'Perseus', 14),
('The Egyptian cow goddess, associated with motherhood.', 'Hathor', 14),
('The shape-shifting sea god in Greek mythology, father of Eidothea.', 'Proteus', 14),
('The three-headed guard dog of the Greek underworld.', 'Cerberus', 14),
('The realm of fire inhabited by fire giants in Norse myth.', 'Muspelheim', 14),
('The Greek goddess of the hunt, twin of Apollo.', 'Artemis', 14),
('The Roman goddess of the hearth, central to family and state.', 'Vesta', 14),
('The legendary Germanic hero who slew the dragon Fafnir.', 'Sigurd', 14),
('The river souls must cross to enter the Greek underworld.', 'Styx', 14),
('The Yoruba trickster god, often depicted with a pipe.', 'Eshu', 14),
('The Greek musician who attempted to rescue his wife Eurydice from Hades.', 'Orpheus', 14),
('The Celtic paradise, also known as \"The Land of the Young.\"', 'Tir Na Nog', 14),
('The Norse trickster god, father of Fenrir and Jormungandr.', 'Loki', 14),
('The Egyptian goddess of magic, wife of Osiris.', 'Isis', 14),
('The titan of time, father of Zeus, who devoured his offspring.', 'Cronus', 14),
('A shape-shifting water spirit in Scottish folklore, often taking equine form.', 'Kelpie', 14),
('In Slavic myth, the household spirit that protects the home.', 'Domovoy', 14),
('The Greek goddess of spring, abducted by Hades.', 'Persephone', 14),
('In Zulu folklore, the mischievous dwarf-like being.', 'Tokoloshe', 14),
('A half-fish, half-human enchantress of European maritime lore.', 'Mermaid', 14),
('The first mortal woman in Greek myth who unleashed evils from a box.', 'Pandora', 14);
-- Revised \"Literature\" (questiontype_id = 15) with multi-word answers

INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('Which English playwright wrote \"Hamlet\" and \"Macbeth\"?', 'William Shakespeare', 15),
('Which Irish author wrote \"Ulysses\" and \"Dubliners\"?', 'James Joyce', 15),
('Which French novel by Victor Hugo follows ex-convict Jean Valjean?', 'Les Misérables', 15),
('Which 1954 novel by William Golding features stranded boys on an island?', 'Lord of the Flies', 15),
('Which South African author wrote \"Cry, the Beloved Country\"?', 'Alan Paton', 15),
('Which Russian novelist wrote \"War and Peace\"?', 'Leo Tolstoy', 15),
('Which classic epic poem is attributed to Homer, featuring the Trojan War?', 'The Iliad', 15),
('Which British author wrote \"Pride and Prejudice\"?', 'Jane Austen', 15),
('Which American wrote \"The Old Man and the Sea\"?', 'Ernest Hemingway', 15),
('Which 1960 novel by Harper Lee focuses on racial injustice in Alabama?', 'To Kill a Mockingbird', 15),
('Which English author created the detective Sherlock Holmes?', 'Arthur Conan Doyle', 15),
('Which Nigerian author penned \"Things Fall Apart\"?', 'Chinua Achebe', 15),
('Which English poet wrote \"Paradise Lost\"?', 'John Milton', 15),
('Which British author wrote the \"Harry Potter\" series?', 'J.K. Rowling', 15),
('Which English novelist wrote \"1984\" and \"Animal Farm\"?', 'George Orwell', 15),
('Which Colombian author wrote \"One Hundred Years of Solitude\"?', 'Gabriel García Márquez', 15),
('Which American author wrote \"Fahrenheit 451\"?', 'Ray Bradbury', 15),
('Which poem by T.S. Eliot begins \"April is the cruellest month\"?', 'The Waste Land', 15),
('Which French novel by Alexandre Dumas features Edmund Dantès?', 'The Count of Monte Cristo', 15),
('Which American wrote \"The Great Gatsby\"?', 'F. Scott Fitzgerald', 15),
('Which British poet wrote \"The Rime of the Ancient Mariner\"?', 'Samuel Taylor Coleridge', 15),
('Which Polish-British novelist wrote \"Heart of Darkness\"?', 'Joseph Conrad', 15),
('Which Swedish author wrote \"Pippi Longstocking\"?', 'Astrid Lindgren', 15),
('Which 8th-century Old English epic poem features the hero who slays Grendel?', 'Beowulf', 15),
('Which American wrote \"Of Mice and Men\" and \"The Grapes of Wrath\"?', 'John Steinbeck', 15),
('Which Brontë sister penned \"Jane Eyre\"?', 'Charlotte Brontë', 15),
('Which 1952 Hemingway novel centres on an old fisherman named Santiago?', 'The Old Man and the Sea', 15),
('Which American wrote \"Invisible Man,\" exploring racial identity?', 'Ralph Ellison', 15),
('Which Japanese author wrote \"Norwegian Wood\" and \"Kafka on the Shore\"?', 'Haruki Murakami', 15),
('Which Canadian author created \"The Handmaid\'s Tale\"?', 'Margaret Atwood', 15),
('Which English author wrote \"Brave New World\"?', 'Aldous Huxley', 15),
('Which African writer won the Nobel Prize, penning \"Death and the King\'s Horseman\"?', 'Wole Soyinka', 15),
('Which German writer is known for \"Faust\"?', 'Johann Wolfgang von Goethe', 15),
('Which British poet wrote \"She Walks in Beauty\"?', 'Lord Byron', 15),
('Which Indian-Canadian wrote \"Life of Pi\"?', 'Yann Martel', 15),
('Which American wrote the \"Divergent\" trilogy?', 'Veronica Roth', 15),
('Which Chilean writer penned \"The House of the Spirits\"?', 'Isabel Allende', 15),
('Which English writer created the fantasy realm of Narnia?', 'C.S. Lewis', 15),
('Which novel by Mary Shelley is subtitled \"The Modern Prometheus\"?', 'Frankenstein', 15),
('Which British writer created Middle-earth with \"The Hobbit\" and \"LOTR\"?', 'J.R.R. Tolkien', 15),
('Which Shakespeare tragedy features King Lear and his three daughters?', 'King Lear', 15),
('Which Russian wrote \"Crime and Punishment\"?', 'Fyodor Dostoevsky', 15),
('Which American wrote \"Beloved,\" set after the American Civil War?', 'Toni Morrison', 15),
('Which German-born poet wrote \"Duino Elegies\" and \"Sonnets to Orpheus\"?', 'Rainer Maria Rilke', 15),
('Which African-born writer was famous for adventure novels like \"When the Lion Feeds\"?', 'Wilbur Smith', 15),
('Which short story master from Argentina wrote \"The Garden of Forking Paths\"?', 'Jorge Luis Borges', 15),
('Which British author wrote \"Wuthering Heights\"?', 'Emily Brontë', 15),
('Which French writer created \"The Three Musketeers\"?', 'Alexandre Dumas', 15),
('Which English poet wrote \"Ozymandias\"?', 'Percy Bysshe Shelley', 15),
('Which US author wrote \"The Color Purple,\" set in rural Georgia?', 'Alice Walker', 15),
('Which Kenyan writer penned \"Weep Not, Child\" and \"A Grain of Wheat\"?', 'Ngũgĩ wa Thiong\'o', 15);

-- Brands & Logos (questiontype_id = 16)
INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('A sports apparel brand with a simple \"Swoosh\" logo.', 'Nike', 16),
('A German auto maker with a circular blue-and-white quadrants logo.', 'BMW', 16),
('A tech giant known for iPhones and a half-eaten fruit logo.', 'Apple', 16),
('A coffeehouse chain using a green siren in its logo.', 'Starbucks', 16),
('A fast-food chain with golden arches shaped like an M.', 'McDonalds', 16),
('A search engine giant using a multicoloured wordmark.', 'Google', 16),
('A microblogging site originally with a blue bird, renamed \"X\" in 2023.', 'Twitter', 16),
('An e-commerce leader whose logo features a smile from \"A\" to \"Z.\"', 'Amazon', 16),
('A German sportswear brand famous for its three-stripes design.', 'Adidas', 16),
('A US soft-drink brand with a red-and-white swirl logo since 1886.', 'Coca Cola', 16),
('A Swiss food and beverage company featuring a nest in its logo.', 'Nestle', 16),
('A Swedish furniture giant with blue and yellow branding.', 'IKEA', 16),
('An American electric car maker with a stylised \"T\" logo.', 'Tesla', 16),
('A British multinational oil company with a green and yellow \"Helios\" logo.', 'BP', 16),
('An airline from Germany featuring a stylized crane on its tail.', 'Lufthansa', 16),
('A Japanese car manufacturer with an oval logo containing a stylised \"T.\"', 'Toyota', 16),
('A South Korean electronics giant known for \"Three Stars\" in its name.', 'Samsung', 16),
('A French cosmetics leader with the slogan \"Because you\'re worth it.\"', 'Loreal', 16),
('A British consumer goods firm with a \"U\" swirl representing its many brands.', 'Unilever', 16),
('A payment card brand with two interlocking circles of red and yellow.', 'MasterCard', 16),
('A Swiss luxury watchmaker known for its crown logo and high-end timepieces.', 'Rolex', 16),
('A fast-food chain whose logo features Colonel Sanders in a red background.', 'KFC', 16),
('A US software giant known for Windows OS.', 'Microsoft', 16),
('A Japanese gaming company behind Mario, with a red wordmark.', 'Nintendo', 16),
('A Japanese conglomerate with a simple uppercase wordmark, maker of PlayStation.', 'Sony', 16),
('An American carmaker featuring a blue oval logo.', 'Ford', 16),
('A ride-hailing service with a stylised black \"U.\"', 'Uber', 16),
('A US oil major that merged brands with a red-and-blue logo.', 'Exxon Mobil', 16),
('A US beverage brand with a red, white, and blue circle logo.', 'Pepsi', 16),
('A British telecom group with a red \"speech mark\" in its logo.', 'Vodafone', 16),
('A French tyre manufacturer whose mascot is the \"Michelin Man.\"', 'Michelin', 16),
('A digital payments brand with a blue wordmark and interlocking Ps.', 'PayPal', 16),
('A Dutch brewer bearing a green bottle and red star logo.', 'Heineken', 16),
('An Italian luxury sports car marque featuring a prancing horse on a yellow shield.', 'Ferrari', 16),
('A British luxury car brand featuring a winged \"B\" logo.', 'Bentley', 16),
('A US microchip maker, known for its blue \"dropped-e\" swirl logo.', 'Intel', 16),
('A streaming platform with a red \"N\" as its logo.', 'Netflix', 16),
('A Spanish fashion retailer with a simple black uppercase wordmark.', 'Zara', 16),
('A French fashion house with the monogram \"LV.\"', 'Louis Vuitton', 16),
('A British engineering company known for bagless vacuum cleaners.', 'Dyson', 16),
('A Chinese tech conglomerate behind WeChat and QQ.', 'Tencent', 16),
('A credit card brand featuring a Centurion in its logo.', 'American Express', 16),
('A major US hotel chain using a stylized red \"M.\"', 'Marriott', 16),
('A Swiss watchmaker whose Speedmaster was used by NASA on the Moon.', 'Omega', 16),
('A British aerospace and auto engineering brand with twin \"R\" monogram.', 'RollsRoyce', 16),
('A German sports car maker from Stuttgart, with a prancing horse crest.', 'Porsche', 16),
('An Emirati airline recognized by its stylized red calligraphy.', 'Emirates', 16),
('An Indian conglomerate with a stylized \"T\" across multiple industries.', 'TATA', 16);
-- Revised \"Food & Drinks\" (questiontype_id = 17) with corrected brand names

INSERT INTO clues (clue_string, answer_string, question_type) VALUES
('Which American fast-food giant is known for the Big Mac?', 'McDonalds', 17),
('Which chain is famous for the flame-grilled Whopper burger?', 'Burger King', 17),
('Which international fast-food brand started in Kentucky, known for fried chicken?', 'KFC', 17),
('Which pizza chain has a red roof logo and once popularized the \"stuffed crust\"?', 'Pizza Hut', 17),
('Which Portuguese-style chicken franchise originated in South Africa?', 'Nandos', 17),
('Which South African burger chain is known for its flame-grilled taste and purple branding?', 'Steers', 17),
('Which local SA chain offers smashburgers, often topped with \"mojo\" sauce?', 'RocoMamas', 17),
('Which family restaurant chain in SA is known for its ranch-style decor and kids\' play areas?', 'Spur', 17),
('Which SA fast-food chain is famous for its T-bone steaks and wacky adverts?', 'Wimpy', 17),
('Which home-style SA dish combines curried mince with an egg-based topping?', 'Bobotie', 17),
('Which sweet, braided South African pastry is deep-fried and syrup-coated?', 'Koeksister', 17),
('Which dried, spiced meat snack is a staple of South African cuisine?', 'Biltong', 17),
('Which SA sausage is commonly cooked on a braai (barbecue)?', 'Boerewors', 17),
('Which simple maize porridge is often served with meat and gravy in SA?', 'Pap', 17),
('Which term is used in SA for a gathering around a grill to cook meat?', 'Braai', 17),
('Which popular SA street food is a hollowed bread loaf filled with curry?', 'Bunny Chow', 17),
('Which sweet SA pudding is made with apricot jam and a creamy sauce?', 'Malva Pudding', 17),
('Which refreshing, malt-based, non-alcoholic beverage is popular in SA?', 'Mageu', 17),
('Which SA dish is made from mealie meal, beans, and sometimes meat?', 'Umngqusho', 17),
('Which brand is known for a green siren logo and popular coffee drinks?', 'Starbucks', 17),
('Which SA brand serves flame-grilled peri-peri chicken, known internationally?', 'Nandos', 17),
('Which local SA dessert is a milk-based tart dusted with cinnamon?', 'Melktert', 17),
('Which dish combines maize meal with a tomato-and-onion relish called \"Chakalaka\"?', 'Pap en Chakalaka', 17),
('Which local brand is famed for \"Cheese Grillers\" and quick roadside meals?', 'Fruit & Veg City', 17),
('Which brand of soda is famously red-and-white and invented in 1886?', 'Coca-Cola', 17),
('Which brand of potato chips is often recognized by a smiling face named Mr. Potato Head in some regions?', 'Lay\'s', 17),
('Which Japanese dish of vinegared rice, often rolled with fish or vegetables, is globally popular?', 'Sushi', 17),
('Which chocolate-hazelnut spread from Italy is beloved worldwide?', 'Nutella', 17),
('Which SA brand of sauces and marinades is known for \"Chutney?\"', 'Mrs Balls', 17),
('Which brand is known for \"Have it Your Way\" burgers in 100 countries?', 'Burger King', 17),
('Which SA chain is known for its flame-grilled peri-peri chicken, starting in Rosettenville?', 'Nandos', 17),
('Which sweet treat is a favourite among SA braais, combining biscuit, caramel, and cream?', 'Peppermint Crisp Tart', 17),
('Which Indian spiced rice dish is popular in SA with meat or vegetables?', 'Biryani', 17),
('Which local sausage is dried and spiced, similar to biltong but thinner?', 'Droewors', 17),
('Which local term refers to a township-style grill spot where meat is braaied?', 'Chisanyama', 17),
('Which sheep\'s head dish gets its name from the \"grin\" formed after cooking?', 'Smiley', 17),
('Which tripe dish is often served with pap in South Africa?', 'Mogodu', 17),
('Which stew is prepared in a three-legged cast iron pot over a fire?', 'Potjiekos', 17),
('Which is a dish of chicken feet and heads called?', 'Walkie Talkies', 17),
('Which deep-fried dough bread is often stuffed with savoury mince or cheese?', 'Vetkoek', 17);